-- =====================================================================
-- Gatekeep Shop — migration 004
-- Payments config, digital goods, configurable perks, order statuses.
-- Run this after 003_grants.sql.
-- =====================================================================

-- ---------------------------------------------------------------------
-- products: digital delivery
-- ---------------------------------------------------------------------
alter table public.products
  add column if not exists delivery_type text not null default 'physical'
    check (delivery_type in ('physical','digital','none'));

alter table public.products
  add column if not exists digital_file_path text;

create index if not exists idx_products_delivery
  on public.products(delivery_type) where delivery_type = 'digital';

-- ---------------------------------------------------------------------
-- store_settings: payment + perks configuration
-- ---------------------------------------------------------------------
alter table public.store_settings
  add column if not exists payment_provider text not null default 'none'
    check (payment_provider in ('none','stripe_link','ton','custom'));

alter table public.store_settings
  add column if not exists payment_url text not null default '';

alter table public.store_settings
  add column if not exists payment_ton_address text not null default '';

alter table public.store_settings
  add column if not exists perks_enabled boolean not null default true;

alter table public.store_settings
  add column if not exists perk_1_text text not null default 'Free shipping over $60';

alter table public.store_settings
  add column if not exists perk_2_text text not null default '30-day easy returns';

alter table public.store_settings
  add column if not exists perk_3_text text not null default 'Secure checkout';

-- ---------------------------------------------------------------------
-- orders: real payment statuses
-- ---------------------------------------------------------------------
alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (status in ('Pending payment','Paid','Processing','In transit','Delivered','Cancelled'));

alter table public.orders
  add column if not exists payment_confirmed_at timestamptz;

alter table public.orders
  add column if not exists delivered_at timestamptz;

-- ---------------------------------------------------------------------
-- Private storage bucket for digital files
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('digital-goods', 'digital-goods', false)
on conflict (id) do nothing;

drop policy if exists "digital_goods_admin_read"   on storage.objects;
drop policy if exists "digital_goods_admin_write"  on storage.objects;
drop policy if exists "digital_goods_admin_modify" on storage.objects;
drop policy if exists "digital_goods_admin_delete" on storage.objects;

-- Only admins can list/read/write in the private bucket.
-- Buyers receive short-lived signed URLs generated by the server.
create policy "digital_goods_admin_read" on storage.objects
  for select to authenticated
  using (bucket_id = 'digital-goods' and public.is_admin(auth.uid()));

create policy "digital_goods_admin_write" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'digital-goods' and public.is_admin(auth.uid()));

create policy "digital_goods_admin_modify" on storage.objects
  for update to authenticated
  using (bucket_id = 'digital-goods' and public.is_admin(auth.uid()))
  with check (bucket_id = 'digital-goods' and public.is_admin(auth.uid()));

create policy "digital_goods_admin_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'digital-goods' and public.is_admin(auth.uid()));

-- ---------------------------------------------------------------------
-- Grant on the new bucket (RLS still gates, but grants must exist)
-- ---------------------------------------------------------------------
grant all on all tables in schema public to anon, authenticated, service_role;
